# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-10 11:45
from __future__ import unicode_literals

from django.db import migrations, models
import utf8field.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='TestModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', utf8field.fields.UTF8FileField(upload_to='media/')),
            ],
        ),
    ]
