# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-29 09:37
from __future__ import unicode_literals

from django.db import migrations, models
import utf8field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dev_example', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestWithMaxContentLengthModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', utf8field.fields.UTF8FileField(max_content_length=1000, upload_to='media/')),
            ],
        ),
    ]
