# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:54
from __future__ import unicode_literals

from django.db import migrations, models
import utf8field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dev_example', '0002_testwithmaxcontentlengthmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='TestCharFieldModel',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', utf8field.fields.UTF8CharField(max_length=100)),
            ],
        ),
    ]
