# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-11 06:58
from __future__ import unicode_literals

from django.db import migrations
import utf8field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dev_example', '0004_auto_20170911_0654'),
    ]

    operations = [
        migrations.AlterField(
            model_name='testcharfieldmodel',
            name='text',
            field=utf8field.fields.UTF8CharField(max_length=2000),
        ),
    ]
