# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 11:53
from __future__ import unicode_literals

from django.db import migrations, models
import utf8field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dev_example', '0006_testtextfieldmodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', utf8field.fields.UTF8TextField()),
            ],
        ),
    ]
