# -*- coding: utf-8 -*-
# Generated by Django 1.11.5 on 2017-09-12 13:43
from __future__ import unicode_literals

from django.db import migrations
import utf8field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dev_example', '0007_message'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='message',
            name='content',
        ),
        migrations.AddField(
            model_name='message',
            name='char',
            field=utf8field.fields.UTF8TextField(blank=True, max_length=2000, null=True),
        ),
        migrations.AddField(
            model_name='message',
            name='file',
            field=utf8field.fields.UTF8FileField(blank=True, max_length=2000, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='message',
            name='text',
            field=utf8field.fields.UTF8CharField(blank=True, max_length=2000, null=True),
        ),
    ]
