# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-05 14:02
from __future__ import unicode_literals

from django.db import migrations, models
import utf8field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dev_example', '0008_auto_20170912_1343'),
    ]

    operations = [
        migrations.CreateModel(
            name='PermissiveMessage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', utf8field.fields.UTF8CharField(blank=True, max_length=2000, null=True)),
                ('char', utf8field.fields.UTF8TextField(blank=True, null=True)),
                ('file', utf8field.fields.UTF8FileField(blank=True, null=True, upload_to=b'')),
            ],
        ),
        migrations.AlterField(
            model_name='message',
            name='file',
            field=utf8field.fields.UTF8FileField(blank=True, four_byte_detection=True, max_length=2000, null=True, upload_to=b''),
        ),
        migrations.AlterField(
            model_name='testmodel',
            name='file',
            field=utf8field.fields.UTF8FileField(four_byte_detection=True, upload_to='media/'),
        ),
        migrations.AlterField(
            model_name='testwithmaxcontentlengthmodel',
            name='file',
            field=utf8field.fields.UTF8FileField(four_byte_detection=True, max_content_length=1000, upload_to='media/'),
        ),
    ]
