# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 10:26
from __future__ import unicode_literals

from django.db import migrations
import utf8field.fields


class Migration(migrations.Migration):

    dependencies = [
        ('dev_example', '0009_auto_20171005_1402'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='char',
            field=utf8field.fields.UTF8CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='message',
            name='text',
            field=utf8field.fields.UTF8TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='permissivemessage',
            name='char',
            field=utf8field.fields.UTF8CharField(blank=True, max_length=2000, null=True),
        ),
        migrations.AlterField(
            model_name='permissivemessage',
            name='text',
            field=utf8field.fields.UTF8TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='testtextfieldmodel',
            name='text',
            field=utf8field.fields.UTF8TextField(four_byte_detection=True),
        ),
    ]
